### ISSUE TITLE
Create the NS record  FAILED!

### ISSUE THREAD

**Issue by thanhnet** [ruzickap/ruzickap.github.io#162]
I follow create ns record but failed:

$ ansible -m cloudflare_dns -c local -i "localhost," localhost -a "zone=networkin9.com record=${BASE_DOMAIN} type=NS value=${NEW_ZONE_NS1} solo=true proxied=no account_email=${CLOUDFLARE_EMAIL} account_api_token=${CLOUDFLARE_API_KEY}"
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "msg": "API bad request; Status: 400; Method: POST: Call: /zones/fe5379ba9ea798b094793c74d4e4d452/dns_records; Error details: code: 81055, error: Non-NS records with that host already exist.; "
}

**Comment by ruzickap** [comment]
May I ask you to show me the commands including the ENV variables:

```bash
echo "${BASE_DOMAIN} | ${NEW_ZONE_NS1}"

set -x

ansible -m cloudflare_dns -c local -i "localhost," localhost -a "zone=networkin9.com record=${BASE_DOMAIN} type=NS value=${NEW_ZONE_NS1} solo=true proxied=no account_email=${CLOUDFLARE_EMAIL}
```
